import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "forge-ui/style.css";
import "./globals.css";
import { auth0 } from "@/lib/auth0";
import { Providers } from "./providers";
import { Navbar } from "./navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
        />
      </head>
      <body className="h-full flex flex-col overflow-hidden">
        <Providers>
          <Navbar user={session?.user ?? null} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
